### ISSUE TITLE
Meta Issue Stories Review for EAG

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/TuringDataStories#137]
### Summary

The reviewers form ethical approval  (issue #118) came back with this suggestion:

" I would suggest that the EAG is given a summary table of projects to review, perhaps after every tenth project, including projects that are published and those that fail the peer review.
 
My suggestion isn't directed at a second layer of reviewing of individual projects; rather, that post-hoc we have some oversight of which projects have been approved and rejected so we can, potentially, make recommendations to the applicants to adjust their decision making, without affecting the existing ethical approvals. In other words, I am suggesting we ask for summaries or, possibly, randomly selected projects, so that we have oversight of their processes, not so that we have oversight of the individual projects, that oversight I agree, should be delegated.""

### What needs to be done?

In this issue we will summarise every review process as a comment. The comment must have the following

- [ ] Story title and link to published version
- [ ] Quick summary of the story
- [ ] Link to review issue and PR
- [ ] Quick summary of the review process, highlighting any discussions that could be relevant for EAG

### Who can help?

Everyone in the management team. 

---

### Updates

Have in here a list of all stories added to the issue as comments:

- [ ] Covid19 deprivation story
- [ ] US election story
